// fichier /home/soleil/GTK/srcbuilder/DDSREP.glade
//2018-03-02.03:05:02

GtkBuilder *builder = gtk_builder_new_from_string (
"<interface>"
"  <requires lib='gtk+' version='3.12'/>"
"  <object class='GtkListStore' id='SFL01'>"
"    <columns>"
"      <!-- column-name col_nom -->"
"      <column type='gchararray'/>"
"      <!-- column-name col_text -->"
"      <column type='gchararray'/>"
"      <!-- column-name col_typ -->"
"      <column type='gchararray'/>"
"      <!-- column-name col_len -->"
"      <column type='gint'/>"
"      <!-- column-name col_dec -->"
"      <column type='gint'/>"
"    </columns>"
"  </object>"
"  <object class='GtkApplicationWindow' id='DDSREP'>"
"    <property name='name'>DDSREP</property>"
"    <property name='can_focus'>False</property>"
"    <property name='border_width'>10</property>"
"    <property name='resizable'>False</property>"
"    <property name='icon_name'>face-angel</property>"
"    <property name='deletable'>False</property>"
"    <child>"
"      <object class='GtkGrid' id='grid2'>"
"        <property name='visible'>True</property>"
"        <property name='can_focus'>False</property>"
"        <child>"
"          <object class='GtkGrid' id='grid4'>"
"            <property name='visible'>True</property>"
"            <property name='can_focus'>False</property>"
"            <property name='halign'>start</property>"
"            <property name='valign'>start</property>"
"            <property name='column_spacing'>10</property>"
"            <child>"
"              <object class='GtkLabel' id='tNOM'>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>False</property>"
"                <property name='label' translatable='yes'>NOM</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>0</property>"
"                <property name='top_attach'>0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkLabel' id='tTEXT'>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>False</property>"
"                <property name='label' translatable='yes'>Texte</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>1</property>"
"                <property name='top_attach'>0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkLabel' id='tTYP'>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>False</property>"
"                <property name='label' translatable='yes'>Type</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>2</property>"
"                <property name='top_attach'>0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkLabel' id='tLEN'>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>False</property>"
"                <property name='label' translatable='yes'>Length</property>"
"                <property name='width_chars'>7</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>3</property>"
"                <property name='top_attach'>0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkLabel' id='tDEC'>"
"                <property name='width_request'>59</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>False</property>"
"                <property name='label' translatable='yes'>Dcml</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>4</property>"
"                <property name='top_attach'>0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkEntry' id='eNOM'>"
"                <property name='name'>NOM</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>True</property>"
"                <property name='max_length'>7</property>"
"                <property name='width_chars'>14</property>"
"                <property name='primary_icon_stock'>gtk-info</property>"
"                <property name='primary_icon_tooltip_text' translatable='yes'>NOm de la Zone Obligatore</property>"
"                <property name='primary_icon_tooltip_markup' translatable='yes'>NOm de la Zone Obligatore</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>0</property>"
"                <property name='top_attach'>1</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkEntry' id='eTEXT'>"
"                <property name='name'>TEXTE</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>True</property>"
"                <property name='max_length'>30</property>"
"                <property name='width_chars'>51</property>"
"                <property name='primary_icon_stock'>gtk-info</property>"
"                <property name='primary_icon_tooltip_text' translatable='yes'>NOm de la Zone Obligatore</property>"
"                <property name='primary_icon_tooltip_markup' translatable='yes'>NOm de la Zone Obligatore</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>1</property>"
"                <property name='top_attach'>1</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkComboBoxText' id='eTYP'>"
"                <property name='name'>TYPE</property>"
"                <property name='width_request'>120</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>False</property>"
"                <items>"
"                  <item id='character' translatable='yes'>character</item>"
"                  <item id='numeric' translatable='yes'>numeric</item>"
"                  <item id='date' translatable='yes'>date</item>"
"                </items>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>2</property>"
"                <property name='top_attach'>1</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkEntry' id='eLEN'>"
"                <property name='name'>Length</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>True</property>"
"                <property name='halign'>center</property>"
"                <property name='max_length'>4</property>"
"                <property name='width_chars'>4</property>"
"                <property name='max_width_chars'>4</property>"
"                <property name='xalign'>0.5</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>3</property>"
"                <property name='top_attach'>1</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkEntry' id='eDEC'>"
"                <property name='name'>Dcml</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>True</property>"
"                <property name='halign'>center</property>"
"                <property name='max_length'>2</property>"
"                <property name='width_chars'>2</property>"
"                <property name='max_width_chars'>4</property>"
"                <property name='xalign'>0.5</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>4</property>"
"                <property name='top_attach'>1</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name='left_attach'>0</property>"
"            <property name='top_attach'>0</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class='GtkTreeView' id='TREEVIEW'>"
"            <property name='width_request'>800</property>"
"            <property name='height_request'>750</property>"
"            <property name='visible'>True</property>"
"            <property name='can_focus'>True</property>"
"            <property name='model'>SFL01</property>"
"            <property name='search_column'>0</property>"
"            <child internal-child='selection'>"
"              <object class='GtkTreeSelection' id='treeview-selection5'/>"
"            </child>"
"            <child>"
"              <object class='GtkTreeViewColumn' id='col_nom'>"
"                <property name='fixed_width'>162</property>"
"                <property name='title' translatable='yes'>NOM</property>"
"                <property name='alignment'>0.5</property>"
"                <child>"
"                  <object class='GtkCellRendererText' id='cellrenderertext6'>"
"                    <property name='weight'>800</property>"
"                    <property name='background_rgba'>rgb(246,232,176)</property>"
"                    <property name='foreground_rgba'>rgb(78,154,6)</property>"
"                  </object>"
"                  <attributes>"
"                    <attribute name='text'>0</attribute>"
"                  </attributes>"
"                </child>"
"              </object>"
"            </child>"
"            <child>"
"              <object class='GtkTreeViewColumn' id='treeviewcolumn5'>"
"                <property name='fixed_width'>10</property>"
"              </object>"
"            </child>"
"            <child>"
"              <object class='GtkTreeViewColumn' id='col_text'>"
"                <property name='fixed_width'>570</property>"
"                <property name='title' translatable='yes'>Texte</property>"
"                <property name='alignment'>0.5</property>"
"                <child>"
"                  <object class='GtkCellRendererText' id='cellrenderertext7'>"
"                    <property name='background_rgba'>rgb(246,232,176)</property>"
"                    <property name='foreground_rgba'>rgb(0,0,0)</property>"
"                  </object>"
"                  <attributes>"
"                    <attribute name='text'>1</attribute>"
"                  </attributes>"
"                </child>"
"              </object>"
"            </child>"
"            <child>"
"              <object class='GtkTreeViewColumn' id='treeviewcolumn6'>"
"                <property name='fixed_width'>10</property>"
"              </object>"
"            </child>"
"            <child>"
"              <object class='GtkTreeViewColumn' id='col_typ'>"
"                <property name='sizing'>autosize</property>"
"                <property name='fixed_width'>128</property>"
"                <property name='title' translatable='yes'>Type</property>"
"                <property name='alignment'>0.5</property>"
"                <child>"
"                  <object class='GtkCellRendererText' id='cellrenderertext8'>"
"                    <property name='xalign'>1</property>"
"                    <property name='background_rgba'>rgb(211,215,207)</property>"
"                    <property name='foreground_rgba'>rgb(241,22,22)</property>"
"                  </object>"
"                  <attributes>"
"                    <attribute name='text'>2</attribute>"
"                  </attributes>"
"                </child>"
"              </object>"
"            </child>"
"            <child>"
"              <object class='GtkTreeViewColumn' id='treeviewcolumn7'>"
"                <property name='fixed_width'>10</property>"
"              </object>"
"            </child>"
"            <child>"
"              <object class='GtkTreeViewColumn' id='col_len'>"
"                <property name='spacing'>1</property>"
"                <property name='sizing'>autosize</property>"
"                <property name='fixed_width'>72</property>"
"                <property name='title' translatable='yes'>Length</property>"
"                <property name='alignment'>0.5</property>"
"                <child>"
"                  <object class='GtkCellRendererText' id='cellrenderertext9'>"
"                    <property name='xalign'>1</property>"
"                    <property name='background_rgba'>rgb(211,215,207)</property>"
"                    <property name='foreground_rgba'>rgb(0,0,0)</property>"
"                  </object>"
"                  <attributes>"
"                    <attribute name='text'>3</attribute>"
"                  </attributes>"
"                </child>"
"              </object>"
"            </child>"
"            <child>"
"              <object class='GtkTreeViewColumn' id='treeviewcolumn8'>"
"                <property name='fixed_width'>10</property>"
"              </object>"
"            </child>"
"            <child>"
"              <object class='GtkTreeViewColumn' id='col_dec'>"
"                <property name='sizing'>autosize</property>"
"                <property name='fixed_width'>60</property>"
"                <property name='title' translatable='yes'>Dcml</property>"
"                <property name='alignment'>0.5</property>"
"                <child>"
"                  <object class='GtkCellRendererText' id='cellrenderertext10'>"
"                    <property name='xalign'>1</property>"
"                    <property name='background_rgba'>rgb(211,215,207)</property>"
"                    <property name='foreground_rgba'>rgb(52,101,164)</property>"
"                  </object>"
"                  <attributes>"
"                    <attribute name='text'>4</attribute>"
"                  </attributes>"
"                </child>"
"              </object>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name='left_attach'>0</property>"
"            <property name='top_attach'>1</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class='GtkGrid' id='grid8'>"
"            <property name='visible'>True</property>"
"            <property name='can_focus'>False</property>"
"            <property name='column_spacing'>25</property>"
"            <child>"
"              <object class='GtkButton' id='bEXIT'>"
"                <property name='label'>gtk-quit</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>True</property>"
"                <property name='receives_default'>True</property>"
"                <property name='use_stock'>True</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>0</property>"
"                <property name='top_attach'>0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkButton' id='bVALIDER'>"
"                <property name='label'>gtk-ok</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>True</property>"
"                <property name='receives_default'>True</property>"
"                <property name='use_stock'>True</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>1</property>"
"                <property name='top_attach'>0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkButton' id='bDELETE'>"
"                <property name='label'>gtk-delete</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>True</property>"
"                <property name='receives_default'>True</property>"
"                <property name='use_stock'>True</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>2</property>"
"                <property name='top_attach'>0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkButton' id='bSLCT'>"
"                <property name='label'>gtk-edit</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>True</property>"
"                <property name='receives_default'>True</property>"
"                <property name='use_stock'>True</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>3</property>"
"                <property name='top_attach'>0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkButton' id='bRTRV'>"
"                <property name='label'>gtk-find</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>True</property>"
"                <property name='receives_default'>True</property>"
"                <property name='use_stock'>True</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>4</property>"
"                <property name='top_attach'>0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkButton' id='bPAGD'>"
"                <property name='label'>gtk-go-down</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>True</property>"
"                <property name='receives_default'>True</property>"
"                <property name='use_stock'>True</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>5</property>"
"                <property name='top_attach'>0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkButton' id='bPAGU'>"
"                <property name='label'>gtk-go-up</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>True</property>"
"                <property name='receives_default'>True</property>"
"                <property name='use_stock'>True</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>6</property>"
"                <property name='top_attach'>0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkButton' id='bLIST'>"
"                <property name='label'>gtk-print</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>True</property>"
"                <property name='receives_default'>True</property>"
"                <property name='use_stock'>True</property>"
"              </object>"
"              <packing>"
"                <property name='left_attach'>7</property>"
"                <property name='top_attach'>0</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name='left_attach'>0</property>"
"            <property name='top_attach'>2</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <object class='GtkBox' id='box2'>"
"            <property name='visible'>True</property>"
"            <property name='can_focus'>False</property>"
"            <property name='spacing'>10</property>"
"            <child>"
"              <object class='GtkLabel' id='tMsg_Name'>"
"                <property name='name'>Msg_Name</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>False</property>"
"                <property name='halign'>start</property>"
"                <property name='hexpand'>True</property>"
"                <property name='justify'>center</property>"
"                <property name='width_chars'>10</property>"
"                <property name='xalign'>0</property>"
"                <attributes>"
"                  <attribute name='foreground' value='#f25915e815e8'/>"
"                </attributes>"
"              </object>"
"              <packing>"
"                <property name='expand'>False</property>"
"                <property name='fill'>True</property>"
"                <property name='position'>0</property>"
"              </packing>"
"            </child>"
"            <child>"
"              <object class='GtkLabel' id='tMsg_text'>"
"                <property name='name'>Msg_text</property>"
"                <property name='visible'>True</property>"
"                <property name='can_focus'>False</property>"
"                <property name='halign'>start</property>"
"                <property name='hexpand'>True</property>"
"                <property name='width_chars'>80</property>"
"                <property name='xalign'>0</property>"
"                <attributes>"
"                  <attribute name='foreground' value='#efef29292929'/>"
"                </attributes>"
"              </object>"
"              <packing>"
"                <property name='expand'>False</property>"
"                <property name='fill'>True</property>"
"                <property name='position'>1</property>"
"              </packing>"
"            </child>"
"          </object>"
"          <packing>"
"            <property name='left_attach'>0</property>"
"            <property name='top_attach'>3</property>"
"          </packing>"
"        </child>"
"      </object>"
"    </child>"
"  </object>"
"</interface>",
-1);
